server {
  listen 80;


  location /gym-frontend/ {
    alias /root/gym-frontend/build/;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /sport-shop-frontend/ {
    alias /root/sport-shop-frontend/build/;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location / {
    alias /root/host-frontend/build/;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /gym-authorization-service/ {
    proxy_pass http://gym-authorization-service:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
