server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html;
    try_files $uri $uri/ /index.html;
  }

  location /gym-frontend/ {
    proxy_pass http://gym-frontend:80/;
  }

  location /sport-shop-frontend/ {
    proxy_pass http://sport-shop-frontend:80/;
  }

  location /gym-authorization-service/ {
    proxy_pass http://gym-authorization-service:3000/;
  }
}
